Tracker:AddLocations("locations/CH1.json")
Tracker:AddLocations("locations/CH2.json")
Tracker:AddLocations("locations/CH3.json")
Tracker:AddLocations("locations/CH4.json")
Tracker:AddLocations("locations/CastleTown.json")
